In [2]:
#1. CARGAR LIBRERÍAS
import pandas as pd
from pycaret.classification import *

In [3]:
#2. CARGAR DATOS
df = pd.read_csv('caso1_churn_clientes.csv')

In [4]:
df.head()

,edad,meses_como_cliente,frecuencia_uso,soporte_llamadas,tipo_plan,usa_app_movil,churn
0,50,42,13,2,Estándar,1,0
1,38,24,10,0,Básico,1,0
2,50,17,9,8,Estándar,1,0
3,32,7,10,0,Premium,1,0
4,23,20,9,6,Estándar,1,0

In [5]:
df['churn'].value_counts()

churn
0    221
1     79
Name: count, dtype: int64

In [6]:
#3. CONFIGURACIÓN DEL ENTORNO
clf = setup(data=df,
            target='churn',
            session_id=123,
            normalize=True,
            categorical_features=['tipo_plan','usa_app_movil'],
            fix_imbalance=True)

In [7]:
#4. COMPARACION DE MODELOS PARA EXPLORAR
best_model = compare_models(sort='AUC')

In [8]:
#5. CREAR EL MODELO ESPECÍFICO 
ridge = create_model('ridge')

In [9]:
#6.AJUSTAR MODELO
tuned_ridge=tune_model(ridge)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [ ]:
#7.EVALUAR LOS RESULTADOS
evaluate_model(ridge)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…