In [1]:
import pandas as pd

from pycaret.regression import *

In [2]:
#1. Cargamos la data

df = pd.read_csv('ds_credito_vehicular.csv')

In [3]:
df.head()

,edad,ingresos_mensuales,estado_civil,historia_credito,nro_creditos_previos,cuota_vs_ingreso,vehiculo_propio,default
0,59,7668,Divorciado,Buena,2,0.64,0,1
1,49,6279,Casado,Buena,2,0.31,1,1
2,35,2722,Soltero,Mala,4,0.41,1,0
3,63,4314,Divorciado,Regular,4,0.57,0,0
4,28,4157,Soltero,Buena,1,0.34,0,0

In [7]:
from pycaret.classification import *

In [9]:
clf = setup(
    data=df,
    target='default',
    session_id=123,
    normalize=True,
    categorical_features=['estado_civil', 'historia_credito', 'vehiculo_propio']
)

In [10]:
best_model = compare_models()

In [11]:
#3. Create model(): Crear un modelo específico
lightgbm = create_model('lightgbm')

In [12]:
#4. Tune_model(): Ajuste automático de hiperparámetros

tuned_lightgbm = tune_model(lightgbm)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [13]:
#5. plot_model(): visualizar el desempeño del modelo

evaluate_model(tuned_lightgbm)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [14]:
#7. Predict_model(): Predicciones sobre nuevos datos en el DF

preds = predict_model(tuned_lightgbm)

print(preds.head())

[LightGBM] [Warning] feature_fraction is set=0.9, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9
[LightGBM] [Warning] bagging_fraction is set=0.5, subsample=1.0 will be ignored. Current value: bagging_fraction=0.5
[LightGBM] [Warning] bagging_freq is set=0, subsample_freq=0 will be ignored. Current value: bagging_freq=0
[LightGBM] [Warning] feature_fraction is set=0.9, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9
[LightGBM] [Warning] bagging_fraction is set=0.5, subsample=1.0 will be ignored. Current value: bagging_fraction=0.5
[LightGBM] [Warning] bagging_freq is set=0, subsample_freq=0 will be ignored. Current value: bagging_freq=0
     edad  ingresos_mensuales estado_civil historia_credito  \
57     60                4457       Casado            Buena
98     55                2147       Casado            Buena
54     34                5659      Soltero          Regular
92     64                2930       Casado            Buena
137    33                4643       Casado            Buena

     nro_creditos_previos  cuota_vs_ingreso  vehiculo_propio  default  \
57                      3              0.32                0        0
98                      2              0.25                1        0
54                      3              0.32                0        0
92                      2              0.31                1        0
137                     0              0.69                0        1

     prediction_label  prediction_score
57                  0            0.8286
98                  0            0.8286
54                  0            0.8286
92                  0            0.8286
137                 0            0.8286

In [ ]:
#8. Save_model/load_model(): Guardar y cargar el modelo

save_model(tuned_lr,'modelo_precio_final')